version: "3.8"

services:

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  service-registry:
    build:
      context: .
      dockerfile: service-registry/Dockerfile
    ports:
      - "8761:8761"

  inventory-service:
    build:
      context: .
      dockerfile: inventory-service/Dockerfile
    depends_on:
      - mongodb
      - kafka
      - service-registry

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    depends_on:
      - kafka
      - service-registry

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    depends_on:
      - service-registry

  shipping-service:
    build:
      context: .
      dockerfile: shipping-service/Dockerfile
    depends_on:
      - service-registry

  notification-service:
    build:
      context: .
      dockerfile: notification-service/Dockerfile
    depends_on:
      - kafka
      - service-registry

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
      - inventory-service
      - order-service
      - payment-service
      - shipping-service
      - notification-service