apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: ecommerce
  labels:
    managed-by: argocd
data:
  SERVER_PORT: "8080"
  SPRING_APPLICATION_NAME: "api-gateway"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://service-registry:8761/eureka/"
  EUREKA_INSTANCE_PREFER_IP_ADDRESS: "true"
  LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_GATEWAY: "DEBUG"
